apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigme-review
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigme-review
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gigme-review
    spec:
      containers:
        - name: gigme-review
          image: ensp1re/gigme-review:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.4"
              memory: 400Mi
            requests:
              memory: "150Mi"
              cpu: "100m"
          ports:
            - name: review
              containerPort: 4007
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: CLUSTER_TYPE
              value: "minikube"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-rabbitmq-endpoint
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-postgres-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-postgres-password
            - name: DATABASE_NAME
              value: "gigme_reviews"
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: "http://gigme-gateway.production.svc.cluster.local:4000"
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-elastic-apm-secret-token
