heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
  - type: http
    id: gigme-api-gateway
    name: gigme API Gateway Service
    schedule: '@every 5s'
    hosts: ["http://gateway:4000/gateway-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-notification
    name: gigme Notification Service
    schedule: '@every 5s'
    hosts: ["http://notifications:4001/notification-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-auth
    name: gigme Auth Service
    schedule: '@every 5s'
    hosts: ["http://auth:4002/auth-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-users
    name: gigme Users Service
    schedule: '@every 5s'
    hosts: ["http://users:4003/user-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-gigs
    name: gigme Gigs Service
    schedule: '@every 5s'
    hosts: ["http://gig:4004/gig-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-chat
    name: gigme Chat Service
    schedule: '@every 5s'
    hosts: ["http://chat:4005/chat-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-orders
    name: gigme Orders Service
    schedule: '@every 5s'
    hosts: ["http://order:4006/order-health"]
    check.request.method: GET
    check.response.status: [200]

  - type: http
    id: gigme-reviews
    name: gigme Reviews Service
    schedule: '@every 5s'
    urls: ["http://review:4007/review-health"]
    check.request.method: GET
    check.response.status: [200]

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
  username: 'elastic'
  password: 'admin1234'