apiVersion: v1
kind: Service
metadata:
  name: gigme-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-postgres
  ports:
    - name: gigme-postgres
      port: 5432
      targetPort: 5432