apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigme-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigme-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: gigme-auth
    spec:
      containers:
      - name: gigme-auth
        image: ensp1re/gigme-auth:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.3'
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: auth
          containerPort: 4002
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-rabbitmq-endpoint
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-mysql-db
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-name
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-api-key
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-api-secret
          - name: CLIENT_URL
            value: 'https://gigmeapp.info'
          - name: API_GATEWAY_URL
            value: 'http://gigme-gateway.production.svc.cluster.local:4000'
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key:  gigme-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elastic-apm-secret-token