apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigme-order
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigme-order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: gigme-order
    spec:
      containers:
      - name: gigme-order
        image: ensp1re/gigme-order:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.4'
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: order
          containerPort: 4006
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: jwt-token
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-rabbitmq-endpoint
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: mongo-database-url
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-name
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-api-key
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: cloud-api-secret
          - name: API_GATEWAY_URL
            value: 'http://gigme-gateway:4000'
          - name: CLIENT_URL
            value: 'https://localhost:3000'
          - name: STRIPE_API_KEY
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: stripe-api-key
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key:  gigme-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elastic-apm-secret-token