apiVersion: v1
kind: Service
metadata:
  name: gigme-gig
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-gig
  ports:
  - name: gig
    port: 4004
    targetPort: 4004
    protocol: TCP