apiVersion: v1
kind: Service
metadata:
  name: gigme-users
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-users
  ports:
  - name: users
    port: 4003
    targetPort: 4003
    protocol: TCP