apiVersion: v1
kind: Service
metadata:
  name: gigme-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-mysql
  ports:
  - name: gigme-mysql
    port: 3306
    targetPort: 3306