apiVersion: v1
kind: Service
metadata:
  name: gigme-chat
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-chat
  ports:
  - name: chat
    port: 4005
    targetPort: 4005
    protocol: TCP