apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigme-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigme-kibana
  template:
    metadata:
      labels:
        app: gigme-kibana
    spec:
      containers:
        - name: gigme-kibana
          image: docker.elastic.co/kibana/kibana:8.12.2
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
          - name: gigme-kibana
            containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: 'http://gigme-elastic.production.svc.cluster.local:9200'
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-elasticsearch-password
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gigme-backend-secret
                  key: gigme-elasticsearch-serviceaccount-token
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config