apiVersion: v1
kind: Service
metadata:
  name: gigme-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-mongo
  ports:
  - name: gigme-mongo
    port: 27017
    targetPort: 27017