apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: production
spec:
  storageClassName: redis-local-storage
  capacity:
    # give it 1gb of memory
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/data1"
