apiVersion: v1
kind: Service
metadata:
  name: gigme-redis
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: gigme-redis
  ports:
    - name: gigme-redis
      port: 6379
      targetPort: 6379
