apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigme-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigme-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: gigme-gateway
    spec:
      containers:
      - name: gigme-gateway
        image: ensp1re/gigme-gateway:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "300m"
            memory: 300Mi
          requests:
            cpu: "100m"
            memory: 150Mi
        ports:
        - name: gateway
          containerPort: 4000
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: SECRET_KEY_ONE
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: secret-key-one
          - name: SECRET_KEY_TWO
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: secret-key-two
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: jwt-token
          - name: CLIENT_URL
            value: 'https://localhost:3000'
          - name: AUTH_BASE_URL
            value: 'http://gigme-auth.production.svc.cluster.local:4002'
          - name: USERS_BASE_URL
            value: 'http://gigme-users.production.svc.cluster.local:4003'
          - name: GIG_BASE_URL
            value: 'http://gigme-gig.production.svc.cluster.local:4004'
          - name: MESSAGE_BASE_URL
            value: 'http://gigme-chat.production.svc.cluster.local:4005'
          - name: ORDER_BASE_URL
            value: 'http://gigme-order.production.svc.cluster.local:4006'
          - name: REVIEW_BASE_URL
            value: 'http://gigme-review.production.svc.cluster.local:4007'
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-redis-host
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: gigme-backend-secret
                key: gigme-elastic-apm-secret-token